### ISSUE TITLE
Storing Images

### ISSUE THREAD

**Issue by ericrkuo** [ubclaunchpad/PromoPal-backend#101]
We want to associate photos with promotions. This is a relatively large issue that still needs to be discussed and planned. Feel free to take a look into [Storing Images Doc](https://docs.google.com/document/d/1SdZkrqNPtxmeyMIFquaUTzC2fOBC61KZuEt8XnzYV8E/edit) for more details and to contribute your ideas there! This is a major feature we plan on supporting next term

**Comment by ld357** [comment]
I like the S3 approach! If it's too slow, I believe we can also AWS CloudFront CDN to make it faster.

**Comment by ld357** [comment]
Also wondering if we'll be storing other photos like user profiles?

**Comment by na-wu** [comment]
We should discuss whether we want the images to be sent to S3 from the FE directly, or if we should abstract that mechanism behind an API endpoint. Off the top of my head we have 3 options:

- Send to S3 directly from FE, no API needed
- Handle files with dedicated endpoint on BE (probably with Multer), API needed
- Convert files to base64 on FE and send them as strings to BE, simpler API needed

I think option 3 is the easiest in terms of implementation + security, but only if images are not being constantly uploaded, and are relatively small in size (<5MB).

**Comment by ericrkuo** [comment]
> Off the top of my head we have 3 options:

Do you know out of these 3 options, which approach is industry standard? And which is more scalable/efficient?

**Comment by na-wu** [comment]
As far as I'm aware, they're all good practices with the differences being in tradeoffs. It's also important to define 'scalable'. A bottleneck I'm concerned about is the one where we handle the image upload through an API. With that said, 

> Send to S3 directly from FE, no API needed

may be the best option since there's no duplicated network I/O. Everything beyond AWS is confidently load balanced, and by definition scalable.

This option is also relatively easy to implement, AWS has a pretty good SDK. Just need to make sure we secure the keys.

**Comment by ericrkuo** [comment]
Ah okay, I like the idea of sending to S3 directly from FE. In the BE, would we store some kind of key in the db so that we know which images are associated with which promotion?

**Comment by ericrkuo** [comment]
> Also wondering if we'll be storing other photos like user profiles?

@ld357 I think this can be its own feature. Once we have the groundwork for the ability to store images, I'm sure we can get to this feature.

**Comment by na-wu** [comment]
> In the BE, would we store some kind of key in the db so that we know which images are associated with which promotion?

Yeah pretty much. We have full control over what the file name will be in S3, and with the way S3 is designed we can just store that key in the DB. It's beautifully simple :)

> Also wondering if we'll be storing other photos like user profiles?
@ld357 If I'm understanding this correctly, are we talking about images associated with a user, such as profile picture/thumbnails?
