### ISSUE TITLE
Authentication Flow

### ISSUE THREAD

**Issue by na-wu** [ubclaunchpad/PromoPal-backend#69]
Firebase actually has REST APIs for authentication, as well as API wrappers included in their SDK,

We could utilize these two endpoints

- https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=[API_KEY]
- https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=[API_KEY]

and because we need API keys, I recommend we wrap these with our own endpoints, and make the server-to-server API calls on the backend, for example with a `POST /login` and `POST /signup` endpoint

Firebase also has built in email validity check (also handles verification that it's a legitimate email, but we can deal with that later), but we should add a frontend mechanism for robustness anyways (same with password, strong passwords only :)

Firebase returns a UUID upon successful registration (which we could then store as the user ID of a user, or add as an attribute to an existing user)

The high level flow should look something like this:

1. User signs up with email + password 
2. POST `/signup` 
3. POST https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=[API_KEY]
4. On success: return UID
5. On fail: return code 400 (EMAIL_EXISTS, INVALID_EMAIL, etc)

High level for sign in is similar:

1. User signs in with email + password 
2. POST `/login` 
3. POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=[API_KEY]
4. On success: return UID
5. On fail: return code 400 (INVALID_PASSWORD)

**Comment by ericrkuo** [comment]
Looks really elegant. So just to double-check for the first high-level flow, if we arrive at success on step 4, then we save the User entity with the corresponding ID returned from firebase?

And also would we be storing the email in the DB?

And for the sign in, does firebase support some kind of expiration_token so that the user doesn't stay signed in the whole time?

**Comment by na-wu** [comment]
Yes we can save the corresponding ID Firebase provides us for the user.
An example here:
![image](https://user-images.githubusercontent.com/36861215/99725580-33451f00-2a6a-11eb-960a-a7f3d9bed23f.png)

We can do anything originally planned with the email, the implementation of Firebase was just to act as a 'detour' between our FE and BE, once the user is successfully registered we can still pass on the email to the backend.

Yes Firebase does have an expiration token, I haven't worked much with refresh tokens and stuff like that but it seems like there is an option to automatically de-authenticate a user.

**Comment by yunishimura0716** [comment]
This is really nice. Thank you for your work. Is this flow applied for some endpoints which require user auth?

**Comment by yunishimura0716** [comment]
When user signup, does user

**Comment by yunishimura0716** [comment]
Is there any additional data in user_profile?

**Comment by ericrkuo** [comment]
@na-wu is it safe to send the password over http request to our backend? 

Also, @yunishimura0716 was interested in doing some work with user authentication and he created a doc here to build up on your ideas https://docs.google.com/document/d/1RdtbGEHxUexCqKS7_DNWQT_68gSe7yL6uEvgYlgNCjs/edit
