### ISSUE TITLE
Handle Missing PlaceID in CachingService and NOT_FOUND for FE Specific Restaurant Request 

### ISSUE THREAD

**Issue by ld357** [ubclaunchpad/PromoPal-backend#89]
We haven't covered the case in which the caching service doesn't contain the placeID. In that case, we should issue a new request to the GooglePlacesService in the FE to retrieve the values.

Merging this issue with the NOT_FOUND error we may encounter when we issue a Places Detail request for a specific restaurant.

Solution: 
Make a new Place Details - ID Refresh SKU request with only the ID field in the parameter. [More info here](https://developers.google.com/places/web-service/place-id#save-id) 
If fails, make a new Places Search with the restaurant name and user-inputted location.

Changes Needed:
- Store the user inputted location in the BE DB Promotion Table
- Handle error case of missing place ID in Caching Service
- Handle error case of NOT_FOUND from Places Details request
- Make a new Refresh SKU function in Google Places API in FE, if fails, makes a new Places Search

**Comment by ericrkuo** [comment]
Sorry closed the wrong one
