### ISSUE TITLE
Separate FE and BE into own repos

### ISSUE THREAD

**Issue by andrewzulaybar** [ubclaunchpad/PromoPal-backend#91]
As we scale up, having the BE and FE in separate repositories might be better. Some good points in favour of this include:

- as brought up in [this PR](https://github.com/ubclaunchpad/foodies/pull/90/), each repo can run its own set of CI commands
- each team is able to work independently from the other already and often one doesn't need to be jumping between files in both the FE and BE folder
- fewer files to manage on your local system

Open to any other thoughts on this! I'm thinking we could probably keep this folder as BE and perhaps just extract the FE files into another repo? If that works, I can look into getting the FE repo set up.

**Comment by ericrkuo** [comment]
That'd be great thanks @andrewzulaybar!
